// <auto-generated />
using GameOfDrones.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameOfDrones.Api.Migrations
{
    [DbContext(typeof(GameDbContext))]
    [Migration("20260916025350_SeedDefaultMoves")]
    partial class SeedDefaultMoves
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("GameOfDrones.Api.Models.Move", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Moves");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Rock"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Paper"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Scissors"
                        });
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.MoveRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BeatsMoveId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MoveId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("BeatsMoveId");

                    b.HasIndex("MoveId");

                    b.ToTable("MoveRules");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BeatsMoveId = 1,
                            MoveId = 2
                        },
                        new
                        {
                            Id = 2,
                            BeatsMoveId = 3,
                            MoveId = 1
                        },
                        new
                        {
                            Id = 3,
                            BeatsMoveId = 2,
                            MoveId = 3
                        });
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("GamesWon")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("GameOfDrones.Api.Models.MoveRule", b =>
                {
                    b.HasOne("GameOfDrones.Api.Models.Move", "BeatsMove")
                        .WithMany()
                        .HasForeignKey("BeatsMoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GameOfDrones.Api.Models.Move", "Move")
                        .WithMany()
                        .HasForeignKey("MoveId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BeatsMove");

                    b.Navigation("Move");
                });
#pragma warning restore 612, 618
        }
    }
}
